### ISSUE TITLE
Add Launcher Icon

### ISSUE THREAD

**Issue by PotatoFi** [freakified/PebbleChecklist#3]
Now that Pebble has released Pebble Firmware v4.0, an app icon for the launcher would be nice. I don't have the skills to do a pull request, but I could at least throw together a quick icon that is ready to go to make things easier, if you'd like to use it. I put it next to a bunch of official Pebble icons to make sure it matches up well and is pixel perfect. [Per the Pebble app icon guidelines](https://developer.pebble.com/guides/migration/migration-guide-4/), it should be a 25x25 PNG. Here it is in both PNG and SVG formats (SVG is zipped for GitHub).

![checklist](https://cloud.githubusercontent.com/assets/19558338/18115053/64e68912-6ef9-11e6-9fd6-dbfd6e0da939.png)

[Checklist.zip](https://github.com/freakified/PebbleChecklist/files/446371/Checklist.zip)

**Comment by tilden** [comment]
Thanks! I will definitely get an icon in soon!

**Comment by tilden** [comment]
Thanks for the icon, I've added it! The new version should be on the store soon
